### ISSUE TITLE
npm run build报错，哪位大神遇到过，builder的版本也升级过试了

### ISSUE THREAD

**Issue by wei1102816471** [SimulatedGREG/electron-vue#1055]
OKAY  take it away `electron-builder`

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
Error: Unresolved node modules: @babel/core, vue, bufferutil, utf-8-validate
    at F:\QZKJ\client\tec-client\node_modules\_app-builder-lib@20.44.4@app-builder-lib\src\util\packageDependencies.ts:112:21
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:725:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at new PromiseSpawn (F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\generators.js:43:17)
    at F:\QZKJ\client\tec-client\node_modules\_bluebird@3.7.2@bluebird\js\release\generators.js:197:21
    at Packager.build (F:\QZKJ\client\tec-client\node_modules\_app-builder-lib@20.44.4@app-builder-lib\src\packager.ts:288:14)
    at build (F:\QZKJ\client\tec-client\node_modules\_app-builder-lib@20.44.4@app-builder-lib\src\index.ts:59:28)
    at build (F:\QZKJ\client\tec-client\node_modules\_electron-builder@20.44.4@electron-builder\src\builder.ts:228:10)
    at F:\QZKJ\client\tec-client\node_modules\_electron-builder@20.44.4@electron-builder\src\cli\cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! teacher@1.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teacher@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\Program Files\node\node_cache\_logs\2020-12-01T03_50_59_790Z-debug.log

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by qiufeihong2018** [comment]
electron-builder配置发出来
