### ISSUE TITLE
执行npm run build的时候报错

### ISSUE THREAD

**Issue by liushuai05** [SimulatedGREG/electron-vue#1065]
##### Describe the issue / bug.
\#执行npm run dev时一切正常，但是执行npm run build的时候报错，错误信息如下（看上去像是下载文件被服务器拒绝了）：

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=2.0.18 appOutDir=build/linux-unpacked
  • downloading     parts=8 size=49 MB url=https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-linux-x64.zip
  • retrying (1)   
  • retrying (2)   
  • retrying (3)   
  ⨯ part download request failed with status code 403
github.com/develar/app-builder/pkg/download.(*Part).doRequest
        /Volumes/data/Documents/app-builder/pkg/download/Part.go:128
github.com/develar/app-builder/pkg/download.(*Part).download
        /Volumes/data/Documents/app-builder/pkg/download/Part.go:66
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadResolved.func1.1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:114
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337
 
Error: /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.<anonymous> (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (node:events:485:26)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
From previous event:
    at _unpack (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/out/electron/ElectronFramework.js:259:18)
    at unpack (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/out/electron/ElectronFramework.js:218:18)
    at ElectronFramework.prepareApplicationStageDirectory (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:115:12)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/platformPackager.ts:180:21
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.doPack (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:197:5)
From previous event:
    at Packager.doBuild (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/graceful-fs/graceful-fs.js:144:16
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:186:23)
From previous event:
    at Packager._build (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (node:internal/timers:463:21)
From previous event:
    at Packager.build (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/electron-builder/src/builder.ts:228:10)
    at /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code 1
npm ERR! path /run/media/ls/59f6b0cd-a75d-4f39-8de5-99db5fc36237/text_object/small_tools
npm ERR! command failed
npm ERR! command sh -c node .electron-vue/build.js && electron-builder

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ls/.npm/_logs/2021-02-16T05_52_34_119Z-debug.log

##### Tell me about your development environment.
  * Node version:  v15.8.0
  * NPM version:7.5.3
  * vue-cli version: 2.9.6
  * Operating System:GNU/Linux  5.10.13-2-MANJARO x86_64

**Comment by liushuai05** [comment]
大概看了一下好像github.com/develar/app-builder/pkg/download这个地址不正确，在github上看到的实际地址应该是github.com/develar/app-builder/tree/master/pkg/download
