### ISSUE TITLE
大神，v2.0太棒了，没有bug

### ISSUE THREAD

**Issue by 423343890123** [SimulatedGREG/electron-vue#1122]
啥时候弄个大a股的api,收费也行，这个太好用了，不用盯盘了

**Comment by JaneYork** [comment]
怎么运行，按照文档操作提示
Error: Failed to find Electron v1.8.0 for darwin-x64 at http://npmmirror.com/mirrors/electron/1.8.0/chromedriver-v1.8.0-darwin-x64.zip
    at Request.<anonymous> (/Users/janeyork/PRO/electron/my-project/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/Users/janeyork/PRO/electron/my-project/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
