### ISSUE TITLE
NODE_ENV not used when not set to "staging" environment

### ISSUE THREAD

**Issue by wdmtech** [SimulatedGREG/electron-vue#144]
##### Describe the issue / bug.

The node environment variable seems to be discarded when not set to `production` when running the `dev` script.

##### How can I reproduce this problem?

Running and setting the environment like so does not set the environment 

`"dev-staging": "cross-env NODE_ENV=staging node tasks/runner.js",`

##### Tell me about your development environment.
  * Node version: v5.10.1
  * NPM version: 4.0.1
  * vue-cli version: (if necessary)
  * Operating System: Windows 7 Professional x64

**Comment by SimulatedGREG** [comment]
@wdmtech 

The `cross-env` command only applies environment variables to the build scripts, and not directly within the webpack environment. You must use the `webpack.DefinePlugin` to set environment variables within your application. See https://github.com/SimulatedGREG/electron-vue/blob/master/template/webpack.renderer.config.js#L141 for reference.

**Comment by wdmtech** [comment]
Gotcha! Cheers @SimulatedGREG :smile_cat:

**Comment by chiaramdelucia** [comment]
When I try using `webpack.DefinePlugin` I get the following error message

```
/Users/chiaradelucia/Spheryx/dragonfly/dist/electron/main.js:2622
  "development" = 'development';
  ^^^^^^^^^^^^^
  ReferenceError: Invalid left-hand side in assignment
      at createScript (vm.js:53:10)
      at Object.runInThisContext (vm.js:95:10)
      at Module._compile (module.js:543:28)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at loadApplicationPackage (/Users/chiaradelucia/Spheryx/dragonfly/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:283:12)
      at Object.<anonymous> (/Users/chiaradelucia/Spheryx/dragonfly/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:325:5)
      at Object.<anonymous> (/Users/chiaradelucia/Spheryx/dragonfly/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:361:3)```
```
I define NODE_ENV with the following in .electron-vue/webpack.render.config.js && .electron-vue/webpack.main.config.js

```
if (process.env.NODE_ENV !== 'production') {
  rendererConfig.plugins.push(
    new webpack.DefinePlugin({
      '__static': `"${path.join(__dirname, '../static').replace(/\\/g, '\\\\')}"`,
      'process.env.NODE_ENV': `"${process.env.NODE_ENV || 'development'}"`,
    })
  )
} 
```

When I define NODE_ENV without the additional quotes like so: ``${process.env.NODE_ENV || 'development'}``, I get a reference error in the Chrome console reading:

```
vue.esm.js?efeb:370 Uncaught ReferenceError: development is not defined
    at eval (vue.esm.js?efeb:370)
    at Object.<anonymous> (renderer.js:740)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at eval (main.js?3b76:1)
    at Object.<anonymous> (renderer.js:1396)
    at __webpack_require__ (renderer.js:680)
    at fn (renderer.js:90)
    at Object.<anonymous> (renderer.js:1313)
    at __webpack_require__ (renderer.js:680)```

Any ideas? TIA!
