### ISSUE TITLE
 no such file or directory, open '.../node_modules/electron-prebuilt/path.txt'

### ISSUE THREAD

**Issue by kolodziejczakM** [SimulatedGREG/electron-vue#21]
After "npm run dev" i got this:

```
"webpack  webpack: bundle is now VALID.

Starting electron...

electron  fs.js:640
            return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                           ^
          
          Error: ENOENT: no such file or directory, open '/home/mk/Desktop/electron-vue/my-project/node_modules/electron-prebuilt/path.txt'
              at Error (native)
              at Object.fs.openSync (fs.js:640:18)
              at Object.fs.readFileSync (fs.js:508:33)
              at Object.<anonymous> (/home/mk/Desktop/electron-vue/my-project/node_modules/electron-prebuilt/index.js:4:42)
              at Module._compile (module.js:556:32)
              at Object.Module._extensions..js (module.js:565:10)
              at Module.load (module.js:473:32)
              at tryModuleLoad (module.js:432:12)
              at Function.Module._load (module.js:424:3)
              at Module.require (module.js:483:17)
"
```
Earlier, during installation (after (sudo) npm install ) i got "gyp errors":

```
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

```

**Comment by SimulatedGREG** [comment]
This is an internal issue with `electron-packager`. In some cases the module does get downloaded, but never has a successful installation (which is why you probably got `node-gyp` errors). Take at look at this workaround for more info ([https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460](https://github.com/electron-userland/electron-prebuilt/issues/69#issuecomment-164636460)). If that workaround doesn't work, you could also try navigating to `my-project/electron-prebuilt` and running `node install.js` manually to complete the installation. Out of curiosity, what OS are you using?

**Comment by kolodziejczakM** [comment]
> Out of curiosity, what OS are you using?
Thx for reply I will try it.
Currently I'm using Linux Mint 17.3

**Comment by SimulatedGREG** [comment]
Yeah I noticed afterwards, haha. This would be the first case that I've heard this problem happen on Linux. I've only ever seen it on Windows.

**Comment by shubhamwaghe** [comment]
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/shubham/programs/mean/electron/electron-music-player/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/home/shubham/programs/mean/electron/electron-music-player/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v6.8.1
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! music-player@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the music-player@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the music-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs music-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls music-player
npm ERR! There is likely additional logging output above.
```
Getting this similar message, on linux mint 17.3

**Comment by SimulatedGREG** [comment]
@shubhamwaghe 

Have you tried to manually run `node index.js` from the modules folder?
