### ISSUE TITLE
npm install doesn't work for me

### ISSUE THREAD

**Issue by Adesubomi** [SimulatedGREG/electron-vue#250]
```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> electron-chromedriver@1.7.1 install /home/spark/Documents/electron-apps/the-home/app-vue-v1.0.1/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> fsevents@1.1.1 install /home/spark/Documents/electron-apps/the-home/app-vue-v1.0.1/node_modules/fsevents
> node install


> electron@1.7.2 postinstall /home/spark/Documents/electron-apps/the-home/app-vue-v1.0.1/node_modules/electron
> node install.js

/home/spark/Documents/electron-apps/the-home/app-vue-v1.0.1/node_modules/electron/install.js:47
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26)
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN my-app@0.0.0 No repository field.
npm WARN my-app@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spark/.npm/_logs/2017-06-06T17_01_31_762Z-debug.log


```

\# npm install always breaks. I've tried yarn also doesn't work
Also tried in sudo, no luck.
Delete `node_modules` and re-installed, no luck either. I'm so confused.
Even if this is not an issue, please help out

\#
* npm@5.0.3
* node@7.10.0
* vue-cli@2.8.2
* ubuntu@16.04

**Comment by SimulatedGREG** [comment]
@Adesubomi 

Closing since this isn't an issue with electron-vue; this pertains to `electron` downloading a prebuilt version of `electron` for development use. In short, if you internet speed isn't quite fast or reliable, then downloading the 40~50mb binary may have so problems. 

Related: https://github.com/electron/electron/issues/9307
