### ISSUE TITLE
NPM errors on running lint script

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#26]
I wasn't entirely sure whether to post this here, at eslint, or eslint-friendly-formatter, so please let me know if this is the wrong place.

When I run the lint script, if there are any problems detected, I get these errors shown below, and the lint:fix script won't function either.

```
D:\David\Documents\my-project  (my-project@0.0.0)
λ npm run lint

> my-project@0.0.0 lint D:\David\Documents\my-project
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app


  ✘  http://eslint.org/docs/rules/semi  Extra semicolon
  D:\David\Documents\my-project\app\src\App.vue:35:37
  import store from 'src/vuex/store';
                                       ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/semi

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! my-project@0.0.0 lint: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.0.0 lint script 'eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app'.
npm ERR! This is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\David\Documents\my-project\npm-debug.log
```

npm-debug.log below:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info prelint my-project@0.0.0
6 info lint my-project@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info my-project@0.0.0 Failed to exec lint script
9 verbose stack Error: my-project@0.0.0 lint: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid my-project@0.0.0
11 verbose cwd D:\David\Documents\my-project
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error my-project@0.0.0 lint: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app`
17 error Exit status 1
18 error Failed at the my-project@0.0.0 lint script 'eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app'.
18 error This is most likely a problem with the my-project package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter app
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs my-project
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls my-project
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

I ran `vue init simulatedgreg/electron-vue my-project`, left everything at defaults, chose ESLinting with Standard, and ran `npm install`. Then I inserted a semi-colon in one of the Vue files to cause a problem, and ran `npm run lint`.

  * Node version: 4.5.0 LTS
  * NPM version: 2.15.9
  * vue-cli version: 2.3.1
  * Operating System: Windows 10 x64

**Comment by SimulatedGREG** [comment]
The is actually more of an issue with [`eslint-plugin-html`](https://github.com/BenoitZugmeyer/eslint-plugin-html). The `npm run lint` command will show any linting errors found in js/vue files and by its default nature, will exit with an error (this is normal). Running `npm run lint:fix` will adjust eslint to make an attempt at fixing any linting errors, but those found inside .vue component files (those being parsed by `eslint-plugin-html`) are not able to be fix automatically. Hope that helps. 😊

**Comment by zxc23** [comment]
I'm relieved that it's working as intended, even though this behaviour seems bizarre to me. You've been very helpful. Thanks!

**Comment by marceloavf** [comment]
These errors are breaking my build, take a look:

```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/CardEmails/Index.vue
Module build failed: SyntaxError: C:/agent/_work/1/s/src/renderer/components/CardEmails/Index.vue: Unexpected token (62:0)
  60 |   },
  61 | };
> 62 | <template>
     | ^
  63 |   <div>
  64 |     <touch-ripple>
  65 |       <div class="bloco-item" v-bind:class="{ 'is-new' : isNew, 'is-selected' : isOpen }">
 @ ./src/renderer/components/CardEmails/Index.vue 8:2-108
 @ ./src/renderer ^\.\/(?!(?:main(\.js)?|.*\.scss)$)
 @ ./test/unit/index.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0  
    chunk    {0} index.html 541 kB [entry]
        [0] ./~/lodash/lodash.js 540 kB {0}
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.32 kB {0}
        [2] (webpack)/buildin/module.js 517 bytes {0}
```

It also breaks when I try to lint:fix, but I can pass though that.
Anything that I can do to make it work properly ?

Thanks!

**Comment by SimulatedGREG** [comment]
```
  60 |   },
  61 | };
> 62 | <template>
```

There shouldn't be any case were JS is outside of a `<script>` tag. Are you missing a closing tag?

**Comment by marceloavf** [comment]
I'll try to find it, I take off --fix and it get back to work, this problem should be in some .vue file, right?

**Comment by jodriscoll** [comment]
@SimulatedGREG – quick inquiry.

You referenced a `npm run lint:fix`, however, you didn't emphasize the definition of what this script object/value pair will _actually_ do. Not helpful to those not in full understanding of whatever script you may be referencing.

Secondly, is there any chance you can provide further details as to your following statement:
> ...and by its default nature, will exit with an error (this is normal)

- The "it" is in reference to what? _(ESLint? Vue? etc...)_
- Can you provide a reference as to why "this is normal"? For those of us experiencing this error for the first time, it doesn't appear to be "normal" when presented in the CLI.
