### ISSUE TITLE
npm install -g vue-cli (errors)

### ISSUE THREAD

**Issue by jfcartier** [SimulatedGREG/electron-vue#271]
I just ran "npm install -g vue-cli" and got these errors. 
Have you ever experienced this? Thanks

```
~/Desktop $ sudo npm install -g vue-cli
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-build -> /usr/local/lib/node_modules/vue-cli/bin/vue-build
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list

> fsevents@1.1.2 install /usr/local/lib/node_modules/vue-cli/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/vue-cli/node_modules/fsevents
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/vue-cli/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/vue-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.9.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/vue-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ vue-cli@2.8.2
added 115 packages and updated 1 package in 9.951s
```

OS : macOS Sierra
Npm : 5.0.3
Node : 7.9.0

**Comment by SimulatedGREG** [comment]
@jfcartier This isn't an electron-vue issue and would be better posted on [`vuejs/vue-cli`](https://github.com/vuejs/vue-cli) or [`strongloop/fsevents`](https://github.com/strongloop/fsevents) issues, so I'll be closing this.

It seems that, for whatever reason, `fsevents` wasn't able to download the prebuilt binary and then tried to build from source manually, which also failed. This is just a guess, but was your internet connect having issues at the time that would effect downloading the hosted binaries on Amazon AWS? There's a chance you could probably just try installing again and it would work.

**Comment by jfcartier** [comment]
Alright thanks for the help @SimulatedGREG
