### ISSUE TITLE
Error when running vue init simulatedgreg/electron-vue my-project

### ISSUE THREAD

**Issue by swan488** [SimulatedGREG/electron-vue#272]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
Hello, 
I've got the following error when trying to run "vue init simulatedgreg/electron-vue my-project“
I'm new to electron and vue, I wonder if you could point out what I need to do to fix this please?

/Users/amy/.vue-templates/simulatedgreg-electron-vue/meta.js:3
const { join } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at getMetadata (/usr/local/lib/node_modules/vue-cli/lib/options.js:43:15)
    at options (/usr/local/lib/node_modules/vue-cli/lib/options.js:15:14)
    at generate (/usr/local/lib/node_modules/vue-cli/lib/generate.js:36:14)
    at /usr/local/lib/node_modules/vue-cli/bin/vue-init:153:5
    at /usr/local/lib/node_modules/vue-cli/node_modules/download-git-repo/index.js:43:22
    at /usr/local/lib/node_modules/vue-cli/node_modules/download/index.js:165:3
    at callback (/usr/local/lib/node_modules/vue-cli/node_modules/each-async/index.js:38:4)
    at onetime (/usr/local/lib/node_modules/vue-cli/node_modules/onetime/index.js:22:12)
    at /usr/local/lib/node_modules/vue-cli/node_modules/download/index.js:156:5

##### How can I reproduce this problem?
\#
Run 
npm install -g vue-cli
Then
vue init simulatedgreg/electron-vue my-project

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: v5.10.1
  * NPM version: 4.2.0
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: OSX 10.11.6

**Comment by swan488** [comment]
Hi, this is resolved by upgrading node to the latest version. Closing the issue now, thanks!
