### ISSUE TITLE
electron-package 

### ISSUE THREAD

**Issue by ibullet-chzn** [SimulatedGREG/electron-vue#300]
hello

electron-package 

There is no package dependency file
Apply the error that was seen in the console when opened

ELECTRON_ASAR.js:119 Uncaught Error: ENOENT, node_modules/.npminstall/axios/0.16.2/axios not found in /Users/administrator/Documents/Electron/qianbao/build/qianbao-darwin-x64/qianbao.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:514:9)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (file:///Users/administrator/Documents/Electron/qianbao/build/qianbao-darwin-x64/qianbao.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:88100)
    at m (file:///Users/administrator/Documents/Electron/qianbao/build/qianbao-darwin-x64/qianbao.app/Contents/Resources/app.asar/dist/electron/renderer.js:1:6823)

**Comment by SimulatedGREG** [comment]
@ibullet-chzn 

At first glance, this seems like a `npm` issue. Can you try deleting `node_modules` and reinstalling, preferably with `yarn`?

**Comment by ibullet-chzn** [comment]
build.config.js 
asar : true , This question will arise
but,
asar : false , is right

**Comment by ibullet-chzn** [comment]
if i set asar : false
when i use Electron Installer builds Windows installers for Electron apps using Squirrel.
It ran for a long time and didn't get the result, probably because the file was too large

**Comment by SimulatedGREG** [comment]
@ibullet-chzn 

I would recommend trying `electron-builder`. There are small edge cases where certain node modules need to be bundled outside of the `asar` archive. `electron-builder` takes care of these edge cases and may solve this issue.

**Comment by ibullet-chzn** [comment]
when i use electron-builder,
i have another error
https://github.com/SimulatedGREG/electron-vue/issues/295

**Comment by ibullet-chzn** [comment]
when i use electron-builder,
npm install ， Get the following error

[7zip-bin-win@2.1.0](./node_modules/.npminstall/7zip-bin/2.1.0/7zip-bin/node_modules/7zip-bin-win) unsupported: Package require os(win32) not compatible with your platform(darwin)
[7zip-bin-win@^2.1.0] optional install error: Package require os(win32) not compatible with your platform(darwin)
[7zip-bin-linux@1.1.0](./node_modules/.npminstall/7zip-bin/2.1.0/7zip-bin/node_modules/7zip-bin-linux) unsupported: Package require os(linux) not compatible with your platform(darwin)
[7zip-bin-linux@^1.1.0] optional install error: Package require os(linux) not compatible with your platform(darwin)

**Comment by ibullet-chzn** [comment]
how to use electron-builder build for win

**Comment by SimulatedGREG** [comment]
@ibullet-chzn 

> [7zip-bin-win@2.1.0](./node_modules/.npminstall/7zip-bin/2.1.0/7zip-bin/node_modules/7zip-bin-win) unsupported: Package require os(win32) not compatible with your platform(darwin)
[7zip-bin-win@^2.1.0] optional install error: Package require os(win32) not compatible with your platform(darwin)
[7zip-bin-linux@1.1.0](./node_modules/.npminstall/7zip-bin/2.1.0/7zip-bin/node_modules/7zip-bin-linux) unsupported: Package require os(linux) not compatible with your platform(darwin)
[7zip-bin-linux@^1.1.0] optional install error: Package require os(linux) not compatible with your platform(darwin)

These are not errors, and they simply warn that those modules for Linux/Windows are not supported on macOS, which is expected behavior.

---

> how to use electron-builder build for win

`electron-builder` requires you to build your application on each platform. So if you need to build for macOS then you have to build on macOS. If you need to build for Windows, then you need  a Windows machine, etc.

You can take advantage of the CI configuration files provided by electron-vue to build all platforms remotely. The CI servers are free to OSS projects and can be automated.

More Info: https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-builder.html#automated-deployments-using-ci
Related: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

Going to close as this isn't a direct issue with electron-vue and more related to `electron-builder`, `asar` archiving, and dependency management.

**Comment by q569608465** [comment]
@ibullet-chzn  Have you solved the problem yet? I use electron-builder, Can you tell me the solution?
