### ISSUE TITLE
ERROR in unknown: Octal literal in strict mode (5457:23)

### ISSUE THREAD

**Issue by ElizurHz** [SimulatedGREG/electron-vue#314]
This error occurred when `npm run build` with electron-builder. 

The error infomation in the terminal: 
```
 ERROR  failed to build renderer process

    Hash: a286059c73585f142a35
    Version: webpack 2.7.0

    Time: 27466ms
                        Asset     Size  Chunks  Chunk Names
    imgs/jsoneditor-icons.svg    36 kB
      fonts/element-icons.ttf  13.2 kB
                         0.js   400 kB       0
                  renderer.js  1.14 MB       1  renderer
                   styles.css   202 kB       1  renderer

    ERROR in unknown: Octal literal in strict mode (5457:23)
    Child html-webpack-plugin for "index.html":
             Asset    Size  Chunks  Chunk Names
        index.html  567 kB       0
    Child extract-text-webpack-plugin:
                            Asset   Size  Chunks  Chunk Names
        imgs/jsoneditor-icons.svg  36 kB
    Child extract-text-webpack-plugin:
                          Asset     Size  Chunks  Chunk Names
        fonts/element-icons.ttf  13.2 kB
```
And the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.1.2
3 info using node@v7.7.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle memdata-electorn@0.0.0~prebuild: memdata-electorn@0.0.0
6 silly lifecycle memdata-electorn@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle memdata-electorn@0.0.0~build: memdata-electorn@0.0.0
8 verbose lifecycle memdata-electorn@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle memdata-electorn@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/elizur/Documents/Bitbucket/memdata-electorn/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/elizur/anaconda/bin:/Users/elizur/documents/scala/bin:/Users/elizur/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/elizur/documents/scala/bin
10 verbose lifecycle memdata-electorn@0.0.0~build: CWD: /Users/elizur/Documents/Bitbucket/memdata-electorn
11 silly lifecycle memdata-electorn@0.0.0~build: Args: [ '-c', 'node .electron-vue/build.js && electron-builder' ]
12 silly lifecycle memdata-electorn@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle memdata-electorn@0.0.0~build: Failed to exec build script
14 verbose stack Error: memdata-electorn@0.0.0 build: `node .electron-vue/build.js && electron-builder`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid memdata-electorn@0.0.0
16 verbose cwd /Users/elizur/Documents/Bitbucket/memdata-electorn
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.7.2
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error memdata-electorn@0.0.0 build: `node .electron-vue/build.js && electron-builder`
22 error Exit status 1
23 error Failed at the memdata-electorn@0.0.0 build script 'node .electron-vue/build.js && electron-builder'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the memdata-electorn package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node .electron-vue/build.js && electron-builder
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs memdata-electorn
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls memdata-electorn
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by SimulatedGREG** [comment]
@ElizurHz 

> ERROR in unknown: Octal literal in strict mode (5457:23)

Just as the error states, there is an octal literal within your code or within a dependency. Using octal literals with `'use strict'` is not allowed. This is not a direct issue with electron-vue so I will be closing.

Related: https://stackoverflow.com/a/34358536/4568234

**Comment by CrzKev** [comment]
Have exactly the same problem.
I can't find the problem have an issue with a plugin (vue2-ace-editor) I use and he said they don't use octal values in his code.
Is there an easy way to debug this.
The error is easily reproducible.
1) vue init simulatedgreg/electron-vue electron-vue-project-test
2) cd electron-vue-project-test
3) npm install
4) npm install --save-dev vue2-ace-editor
5) Add to the main.js 
  import Vue2AceEditor from 'vue2-ace-editor'
  Vue.use(Vue2AceEditor)
6) npm run build ## (**side note npm run dev WORKS**)
![image](https://user-images.githubusercontent.com/33102056/36273724-bc1ee2fc-1285-11e8-805b-61de260fc6c4.png)
