### ISSUE TITLE
npm run build:darwin err 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by BusyHe** [SimulatedGREG/electron-vue#328]
```
 OKAY  take it away `electron-packager`

Packaging app for platform darwin x64 using electron v1.7.5

 ERROR  `electron-packager` says...

Error: Command failed: npm prune --production
Unhandled rejection RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.test (native)
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/busyhe/.npm/_logs/2017-07-27T03_33_40_171Z-debug.log

```
  * Node version:v6.11.0
  * NPM version:5.3.0
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by BusyHe** [comment]
@SimulatedGREG help

**Comment by develar** [comment]
Please consider to use electron-builder and yarn.

**Comment by alexyan** [comment]
+1 help
