### ISSUE TITLE
vue init simulatedgreg/electron-vue my-project FAILS with SyntaxError

### ISSUE THREAD

**Issue by ricorx7** [SimulatedGREG/electron-vue#340]
##### Describe the issue / bug.
MacBook-Pro:electron-vue XXX$ vue init simulatedgreg/electron-vue my-project

/Users/XXX/.vue-templates/simulatedgreg-electron-vue/meta.js:3
const { join } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at getMetadata (/usr/local/lib/node_modules/vue-cli/lib/options.js:43:15)
    at options (/usr/local/lib/node_modules/vue-cli/lib/options.js:15:14)
    at generate (/usr/local/lib/node_modules/vue-cli/lib/generate.js:36:14)
    at /usr/local/lib/node_modules/vue-cli/bin/vue-init:153:5
    at /usr/local/lib/node_modules/vue-cli/node_modules/download-git-repo/index.js:43:22
    at /usr/local/lib/node_modules/vue-cli/node_modules/download/index.js:165:3
    at callback (/usr/local/lib/node_modules/vue-cli/node_modules/each-async/index.js:38:4)
    at onetime (/usr/local/lib/node_modules/vue-cli/node_modules/onetime/index.js:22:12)
    at /usr/local/lib/node_modules/vue-cli/node_modules/download/index.js:156:5

I have run a vue.js application on this computer.
I have run electron on this computer.
I have run a vue.js application with electron on this computer, so i believe i have everything installed to work.

##### How can I reproduce this problem?
Run 
> vue  init simulatedgreg/electron-vue my-project

##### Tell me about your development environment.
  * Node version: 5.4.0
  * NPM version: 3.3.12
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: OSX El Capitan v10.11.6

**Comment by re-fort** [comment]
@ricorx7 
Node v5.4.0 does not support destructuring assignment.
Upgrade it.
http://node.green/#ES2015-syntax-destructuring--assignment

**Comment by ricorx7** [comment]
Got it.  Updated my Node to v8.2.1 and it is fixed.

> sudo npm cache clean -f
> sudo npm install -g n
> sudo n stable
