### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ozee31** [SimulatedGREG/electron-vue#35]
##### Describe the issue / bug.
\# I have a problem when install packages. When i run `npm run install` i have 2 problems :

```
npm WARN prefer global npm@3.10.8 should be installed with -g

> nslog@3.0.0 install D:\Dev\test\demo-vuejs-electron\node_modules\nslog
> node-gyp rebuild


D:\Dev\test\demo-vuejs-electron\node_modules\nslog {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Dev\test\demo-vuejs-electron\node_modules\nslog
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

and

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN electron-devtools-installer@1.1.5 requires a peer of electron-prebuilt@^1.2.1 but none was installed.
npm WARN vueelectron@0.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev\test\demo-vuejs-electron\npm-debug.log
```

##### Tell me about your development environment.
  * Node version: 6.7.0
  * NPM version: 3.10.3
  * vue-cli version: 2.4.0
  * Operating System: Windows 10 x64

**Comment by SimulatedGREG** [comment]
@ozee31 

Based on the error log you provided it would seem you need to have python installed on your system.
```bash
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

 It was also seem that `fsevents`(which is a dependency of webpack) isn't compatible with your OS. 
```bash
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Both errors may have occurred because you are running the latest version on Node.js (which barely came out [3 days ago](https://github.com/nodejs/node/releases/tag/v6.7.0)). Usually big modules like  `fsevents` need a little time to support any breaking changes a newer version of Node.js may have produced.  I'd recommend using `node@6.3.0`, but you may get it working with something higher.

**Comment by wdmtech** [comment]
This worked for me:

Upgrade npm on Windows 

https://github.com/felixrieseberg/npm-windows-upgrade

And then install windows-build-tools

https://github.com/felixrieseberg/windows-build-tools

**Comment by ozee31** [comment]
ok think you, I'm going to try

**Comment by ozee31** [comment]
It's works

**Comment by komplexb** [comment]
Experienced this on WIndows today, and used @wdmtech tip @ https://github.com/SimulatedGREG/electron-vue/issues/35#issuecomment-251936450 to solve it. 

Might be a good idea to add it to the docs and the readme as a prereq for using electron-vue on Windows. Or at least added to the FAQ so users don't have to hunt down closed issues to arrive at a solution.

**Comment by SimulatedGREG** [comment]
@komplexb 

It actually is noted on the readme under "A Note for Windows Users".

**Comment by komplexb** [comment]
@SimulatedGREG oops my bad.

**Comment by qq254963746** [comment]
I got the same error on MacOS
