### ISSUE TITLE
failed `npm run build`

### ISSUE THREAD

**Issue by fluency03** [SimulatedGREG/electron-vue#362]
##### Describe the issue / bug.

I just started new project by cloning from `electron-vue` repo.  I did some changes regarding `vue` files.  When I tried to build it using `npm run build`, I got the following error.  

There are two steps: 
- `node .electron-vue/build.js`, this is Passing
- `electron-builder`, this is Failing

It is failing both on my laptop and on TravisCI. Anyone has encountered this issue?

```
npm run build

> argent-client@0.0.0 build /Users/fluency03/Workplace/github/argent-client
> node .electron-vue/build.js && electron-builder


 ___              __                        __                       ___       __
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/

  ✔ building main process
  ✔ building renderer process


Hash: 1c04b353835f2eb069e4
Version: webpack 2.7.0
Time: 1869ms
  Asset     Size  Chunks             Chunk Names
main.js  1.08 kB       0  [emitted]  main

Hash: 547e95c078680d8e8758
Version: webpack 2.7.0
Time: 15014ms
              Asset       Size  Chunks                    Chunk Names
 fonts/ionicons.eot     121 kB          [emitted]
  imgs/ionicons.svg     334 kB          [emitted]  [big]
 fonts/ionicons.ttf     189 kB          [emitted]
fonts/ionicons.woff    67.9 kB          [emitted]
        renderer.js     109 kB       0  [emitted]         renderer
         styles.css     214 kB       0  [emitted]         renderer
         index.html  355 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0
Child extract-text-webpack-plugin:
                  Asset     Size  Chunks  Chunk Names
     fonts/ionicons.eot   121 kB
      imgs/ionicons.svg   334 kB
     fonts/ionicons.ttf   189 kB
    fonts/ionicons.woff  67.9 kB


 OKAY  take it away `electron-builder`

electron-builder 19.22.1
Installing app dependencies for arch x64 to /Users/fluency03/Workplace/github/argent-client/app
Packaging for darwin x64 using electron 1.7.5 to build/mac
Downloading tmp-37159-1-SHASUMS256.txt-1.7.5
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Error: Application entry file "dist/main.js" in the "/Users/fluency03/Workplace/github/argent-client/build/mac/argent-client.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/util/asarUtil.ts:225:12)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/util/asarUtil.ts:251:11
    at Generator.next (<anonymous>)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at checkFileInArchive (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/util/asarUtil.js:52:22)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/platformPackager.ts:301:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/platformPackager.js:376:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/platformPackager.ts:349:16
    at Generator.next (<anonymous>)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/platformPackager.js:394:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/platformPackager.ts:194:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at MacPackager.doPack (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/platformPackager.js:254:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/macPackager.ts:92:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/macPackager.js:190:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/packager.ts:253:24
From previous event:
    at Packager.doBuild (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/packager.js:340:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/packager.ts:184:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/packager.js:259:11)
    at /Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/builder.ts:266:40
    at Generator.next (<anonymous>)
    at build (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/src/cli/cli.ts:49:4)
From previous event:
    at build (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/builder.js:69:21)
    at loadEnv.then (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/cli/cli.js:155:79)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Object.args [as handler] (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/cli/cli.js:155:68)
    at Object.self.runCommand (/Users/fluency03/Workplace/github/argent-client/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/fluency03/Workplace/github/argent-client/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/fluency03/Workplace/github/argent-client/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/fluency03/Workplace/github/argent-client/node_modules/electron-builder/out/cli/cli.js:151:465)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! argent-client@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the argent-client@0.0.0 build script 'node .electron-vue/build.js && electron-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the argent-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .electron-vue/build.js && electron-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs argent-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls argent-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fluency03/Workplace/github/argent-client/npm-debug.log
```

**Comment by SimulatedGREG** [comment]
@fluency03 

> Error: Application entry file "dist/main.js" in the "/Users/fluency03/Workplace/github/argent-client/build/mac/argent-client.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.

Since you made some changes, make sure to check that the webpack output and the package.json main setting are the same. electron-vue by default outputs to `./dist/electron/main.js` and the package.json has `main: 'dist/electron/main.js`.

**Comment by fluency03** [comment]
I only changed the stuff under `src/renderer/` not other places.  It should not have impact on build and deploy right?

**Comment by fluency03** [comment]
@SimulatedGREG I finally found the problem!

I don't know why, when I create a new project, the `app/` directory is still being created.   I thought it should not exist right?    All `app/` stuff are moved into `src/` and there should be only one `package.json`.       

After I delete the template `app/` folder.   The build works fine!

Is it a bug to be fixed or I am doing something wrong?

**Comment by SimulatedGREG** [comment]
@fluency03 

This is related to a previous `vue-cli` issue. See #299 for more info.
