### ISSUE TITLE
npm run build:win32 failed

### ISSUE THREAD

**Issue by 0604hx** [SimulatedGREG/electron-vue#364]
Hi, I try to build app on Windows with electron-vue(init project for test), and I got these errors:
```
Hash: 7719a86a6f07356db80d
Version: webpack 2.7.0
Time: 1026ms
  Asset     Size  Chunks             Chunk Names
main.js  1.08 kB       0  [emitted]  main

Hash: f333d5a0e7b8262f2821
Version: webpack 2.7.0
Time: 7240ms
        Asset       Size  Chunks             Chunk Names
imgs/logo.png    61.9 kB          [emitted]
  renderer.js     100 kB       0  [emitted]  renderer
   styles.css    1.25 kB       0  [emitted]  renderer
   index.html  352 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0


 OKAY  take it away `electron-packager`

Packaging app for platform win32 x64 using electron v1.7.5

 ERROR  `electron-packager` says...

Error: Command failed: npm prune --production
npm WARN my-project@0.0.0 No repository field.
npm WARN my-project@0.0.0 No license field.

npm ERR! May not delete: C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app\node_modules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\software\nodejs\cache\_logs\2017-08-21T07_22_48_788Z-debug.log
```

I use electron-packager.

##### Describe the issue / bug.

```
3410 verbose unlock done using F:\software\nodejs\cache\_locks\staging-6cf9e25e62c0e752.lock for C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app\node_modules\.staging
3411 warn my-project@0.0.0 No repository field.
3412 warn my-project@0.0.0 No license field.
3413 verbose stack Error: May not delete: C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app\node_modules\.bin
3413 verbose stack     at gentlyRm (F:\software\nodejs\node_modules\npm\lib\utils\gently-rm.js:49:15)
3413 verbose stack     at gentlyRmBinRoot (F:\software\nodejs\node_modules\npm\lib\unbuild.js:86:12)
3413 verbose stack     at cb (F:\software\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
3413 verbose stack     at LOOP (F:\software\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
3413 verbose stack     at F:\software\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
3413 verbose stack     at F:\software\nodejs\node_modules\npm\lib\utils\gently-rm.js:70:40
3413 verbose stack     at F:\software\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
3413 verbose stack     at F:\software\nodejs\node_modules\npm\node_modules\iferr\index.js:11:16
3413 verbose stack     at F:\software\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
3413 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
3414 verbose cwd C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app
3415 verbose Windows_NT 10.0.15063
3416 verbose argv "F:\\software\\nodejs\\node.exe" "F:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prune" "--production"
3417 verbose node v8.4.0
3418 verbose npm  v5.3.0
3419 error May not delete: C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app\node_modules\.bin
3420 verbose exit [ 1, true ]
```

##### How can I reproduce this problem?

I could not find `C:\Users\ADMINI~1\AppData\Local\Temp\electron-packager\win32-x64\my-project-win32-x64\resources\app\node_modules\.bin` directory on my FileSystem...

##### Tell me about your development environment.
  * Node version: 8.4.0 x64
  * NPM version: 
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: windows 10 x64

Thanks

**Comment by SimulatedGREG** [comment]
@0604hx 

There is a current bug with `npm@5.3.0`, specifically dealing with the `prune` usage. Try using with 5.2.0.
```bash
npm install -g npm@5.2.0
```

**Comment by develar** [comment]
@SimulatedGREG I suggest you just say "do not use NPM, please use yarn instead". Bugs in the NPM are persistent.

**Comment by develar** [comment]
electron-builder will change current recommendation to 
```
Please use [Yarn](http://yarnpkg.com/), npm is strongly not recommended.
```

due to new and new issues about buggy NPM.

**Comment by 0604hx** [comment]
Thanks, I degrade to npm@5.2.0 and build successful.

BTW, `yarn`  does not work well while npm@5.3.0
