### ISSUE TITLE
npm script: "lint:fix" produces error

### ISSUE THREAD

**Issue by SimulatedGREG** [SimulatedGREG/electron-vue#379]
`eslint@4.6.0` introduce a refactored API that `eslint-plugin-html` relied upon. Current workaround is to downgrade to 4.5.0.

```bash
yarn add -D eslint@4.5.0

# or 

npm install --save-dev eslint@4.5.0
```

**Please know that you will see the below error when installing dependencies (during the `postinstall` hook), but you can continue with developing your application.**

```bash
sourceText.startsWith is not a function
TypeError: sourceText.startsWith is not a function
    at Function.SourceCodeFixer.applyFixes (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/util/source-code-fixer.js:76:26)
    at Function.SourceCodeFixer.applyFixes (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint-plugin-html/src/index.js:152:23)
    at Linter.verifyAndFix (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/linter.js:1258:43)
    at processText (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli-engine.js:196:34)
    at processFile (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli-engine.js:245:18)
    at executeOnFile (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli-engine.js:585:25)
    at fileList.forEach.fileInfo (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli-engine.js:622:13)
    at Array.forEach (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli-engine.js:621:18)
    at Object.execute (/Users/gregholguin/Documents/Projects/playground/k/node_modules/eslint/lib/cli.js:181:107)
```

Related: https://github.com/eslint/eslint/issues/9204

**Comment by SimulatedGREG** [comment]
Fixed in https://github.com/BenoitZugmeyer/eslint-plugin-html/commit/48eeac7d1cb92d5ded8d8e95ac245cd352c35ca5
