### ISSUE TITLE
ZeroRPC Port Issue

### ISSUE THREAD

**Issue by chiaramdelucia** [SimulatedGREG/electron-vue#396]
##### Describe the issue / bug.

I added this to a closed issue [here](https://github.com/SimulatedGREG/electron-vue/issues/302), but I wasn't sure if you receive notifications for closed issues, so I apologize if this is redundant. 

###### 1. In package.json add:
```
dependecies: {
     "zerorpc": "git+https://github.com/fyears/zerorpc-node.git"
},
dev-dependencies{
    electron-packager 9.0.1 
    electron 1.7.6
}
````
###### 2. npm install with this specific command
```npm install --runtime=electron --target=1.7.6```

###### 3. Add the following code ABOVE the electron process in *src/main/main.js*
```
// py process

const PY_DIST_FOLDER = 'pycalcdist';
const PY_FOLDER = 'pycalc';
const PY_MODULE = 'api'; // without .py suffix

let pyProc = null;
let pyPort = null;

const guessPackaged = () => {
  const fullPath = path.join(PY_DIST_FOLDER);
  return require('fs').existsSync(fullPath);
};

const getScriptPath = () => {
  if (!guessPackaged()) {
    return path.join(PY_FOLDER, PY_MODULE + '.py');
  }
  if (process.platform === 'win32') {
    return path.join(PY_DIST_FOLDER, PY_MODULE, PY_MODULE + '.exe');
  }
  return path.join(PY_DIST_FOLDER, PY_MODULE, PY_MODULE);
};

const selectPort = () => {
  pyPort = 4242;
  return pyPort;
};

const createPyProc = () => {
  const script = getScriptPath();
  const port = '' + selectPort();

  if (guessPackaged()) {
    pyProc = require('child_process').execFile(script, [port]);
  } else {
    pyProc = require('child_process').spawn('python', [script, port]);
  }

  if (pyProc != null) {
    // console.log(pyProc)
    console.log('child process success on port ' + port);
  }
};

const exitPyProc = () => {
  pyProc.kill();
  pyProc = null;
  pyPort = null;
};

app.on('ready', createPyProc);
app.on('will-quit', exitPyProc);
```

###### 5. Inside *api.py* add the following code. Inside *thing* function, and a path to a local image:

```
from __future__ import print_function
from calc import calc as real_calc
import sys
import zerorpc

class CalcApi(object):
    def calc(self, text):
        """based on the input text, return the int result"""
        try:
            return real_calc(text)
        except Exception as e:
            return 0.0    
    def echo(self, text):
        """echo any text"""
        return text
    def thing(self):
        image = 'ADD PATH TO A LOCAL IMAGE HERE '
        return image

def parse_port():
    port = 4242
    try:
        port = int(sys.argv[1])
    except Exception as e:
        pass
    return '{}'.format(port)

def main():
    addr = 'tcp://127.0.0.1:' + parse_port()
    s = zerorpc.Server(CalcApi())
    s.bind(addr)
    print('start running on {}'.format(addr))
    s.run()

if __name__ == '__main__':
    main()
```

###### 6. Add a .vue file with the following code:
```
<template>
  <div>
    <img v-on:click='img' v-bind:src='imgPreview'></img>
  </div>
</template>

<script>
import zerorpc from 'zerorpc';

export default {
  data() {
    return {
      imgPreview: 'https://images.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.yb6JrZkTl4WccjjEEU3HegEsEC%26pid%3D15.1&f=1'
    };
  },
  methods: {
    img: function () {
      const client = new zerorpc.Client();
      client.connect("tcp://127.0.0.1:4242");
      client.invoke('thing', (error, res) => {
        if (error) {
          console.log(error);
        } else {
          this.imgPreview = res;
        }
      });
    },
  }
};
</script>
```

##### Tell me about your development environment.
  * Node version: 6.11.3
  * NPM version: 5.4.1
  * vue-cli version: (if necessary)
  * Operating System: Ubuntu 16.04

# Thank you so, so much for your time.

**Comment by k29** [comment]
Hi Chiara,

Did you manage to get zerorpc working with electron? On integrating them, (using your steps above, or otherwise), I got the following error. Any clues, as to what might be wrong?

```
┏ Electron -------------------

  child process success on port 4242

┗ ----------------------------

┏ Electron -------------------

  stderr: Traceback (most recent call last):
    File "pycalc/api.py", line 34, in <module>
      main()
    File "pycalc/api.py", line 28, in main
      s.bind(addr)
    File "/Users/kaustubh.n/anaconda/lib/python3.6/site-packages/zerorpc/socket.py", line 43, in bind
      return self._events.bind(endpoint, resolve)
    File "/Users/kaustubh.n/anaconda/lib/python3.6/site-packages/zerorpc/events.py", line 325, in bind
      r.append(self._socket.bind(endpoint_))
    File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5653)
    File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
  zmq.error.ZMQError: Address already in use


┗ ----------------------------

┏ Electron -------------------

  child process exited with code 1

┗ ----------------------------
```

**Comment by chiaramdelucia** [comment]
@k29 I'm so sorry I didn't see this until just now. I have gotten zeroRPC to work with this package, actually. I'm not exactly sure what's going on with your code. Looks like the connection to zeroRPC is good. What zeroRPC package are you using? I recommend using the modified package that fyears[https://github.com/fyears/electron-python-example] uses. I think the zeroMQ version is the main issue. Follow the steps inside that repo with the electron runtime as well! That is pretty important. 

Again, sorry such a late reply. Hope you got it working!

**Comment by k29** [comment]
Hey, no worries, I managed to get it working. :)
