### ISSUE TITLE
How to use postcss with vue-loader?

### ISSUE THREAD

**Issue by snovey** [SimulatedGREG/electron-vue#402]
#### Hi, there. I config postcss with css-loader:
```javascript
test: /\.css$/,
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [{
    loader: 'css-loader'
  }, {
    loader: 'postcss-loader',
    options: {
      plugins: (loader) => [
        require('postcss-cssnext')(),
        require('precss')
      ]
    }
  }]
})
```
It works well, and then I config this with vue-loader:
```javascript
test: /\.vue$/,
use: {
  loader: 'vue-loader',
  options: {
    extractCSS: process.env.NODE_ENV === 'production',
    postcss: {
      options: {
        plugins: (loader) => [
          require('postcss-cssnext')()
        ]
      }
    },
    loaders: {
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
      scss: 'vue-style-loader!css-loader!sass-loader',
    }
  }
}
```
But it doesn't work and no warning or error output. What should I do?
  * Node version: 6.11.0
  * NPM version: 4.6.1
  * vue-cli version: 2.8.2
  * Operating System: Windows 10

**Comment by snovey** [comment]
I have changed my config file, and then support postcss, here is my config:
```javascript
test: /\.vue$/,
use: {
  loader: 'vue-loader',
  options: {
    extractCSS: true,
    postcss: [
      require('postcss-cssnext')(),
      require('precss')()
    ],
    loaders: {
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
      scss: 'vue-style-loader!css-loader!sass-loader'
    }
  }
}
```
But  when I write css like this:
```css
.title {
  color: #2c3e50;
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 6px;
  &:hover {
    background-color: #4fc08d;
  }
}
```
this will cause an error:
```javascript
ERROR in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-78145104","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage.vue
Module build failed: TypeError: node.parent.after is not a function
    at module.exports (/home/snovey/Documents/my-electron/node_modules/postcss-nesting/lib/transform-nesting-rule.js:18:29)
    at module.exports (/home/snovey/Documents/my-electron/node_modules/postcss-nesting/lib/transform.js:16:3)
    at /home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:114:22)
    at Rule.walk (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:147:21)
    at /home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:150:32
    at Root.each (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:147:21)
    at /home/snovey/Documents/my-electron/node_modules/postcss-nesting/index.js:9:24
    at LazyResult.run (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:228:20)
    at Promise (<anonymous>)
    at LazyResult.async (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:225:27)
    at LazyResult.then (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:131:21)
    at loadPostcssConfig.then.config (/home/snovey/Documents/my-electron/node_modules/vue-loader/lib/style-compiler/index.js:58:8)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-78145104","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage.vue 4:14-310 13:3-17:5 14:22-318
 @ ./src/renderer/components/LandingPage.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```
Then I try to do the same thing with [webpack](https://github.com/vuejs-templates/webpack) and there is no error. Both of them are same postcss version:
- "postcss-cssnext": "^3.0.2",
- "postcss-loader": "^2.0.6",
- "precss": "^2.0.0",

Who can help me?

**Comment by snovey** [comment]
I have solve this problem.
It need update vue-loader to 13.x.
