### ISSUE TITLE
When npm install on windows7, I  got an issue 

### ISSUE THREAD

**Issue by anuxs** [SimulatedGREG/electron-vue#419]
#### Found an issue or bug with electron-vue? Tell me all about it!
when npm install on windows7, got an issue .

##### Describe the issue / bug.
\#
1945 silly fetchPackageMetaData error for webpack@^3.5.2 Unexpected end of input at 1:72287
1945 silly fetchPackageMetaData ","optimist":"0.2.x","uglify-js":"2.2.x","async":"0.1.x","enhanced-re
1945 silly fetchPackageMetaData                                                                      ^
1946 verbose stack SyntaxError: Unexpected end of input at 1:72287
1946 verbose stack ","optimist":"0.2.x","uglify-js":"2.2.x","async":"0.1.x","enhanced-re
1946 verbose stack                                                                      ^
1946 verbose stack     at Object.parseJSON (C:\nodejs\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\node_modules\jju\lib\parse.js:745:13)
1946 verbose stack     at parse (C:\nodejs\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\index.js:10:13)
1946 verbose stack     at consumeBody.call.then.buffer (C:\nodejs\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
1946 verbose stack     at <anonymous>
1946 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
1947 verbose cwd c:\nodejs\electron-vue-0929
1948 verbose Windows_NT 6.1.7601
1949 verbose argv "C:\\nodejs\\nodejs\\node.exe" "C:\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1950 verbose node v8.5.0
1951 verbose npm  v5.3.0
1952 error Unexpected end of input at 1:72287
1952 error ","optimist":"0.2.x","uglify-js":"2.2.x","async":"0.1.x","enhanced-re
1952 error                                                                      ^
1953 verbose exit [ 1, true ]

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:8.5.0
  * NPM version:5.3.0
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: Windows 7 32bit

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose npm-session 24edb107070ebde0
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall mylvue@0.0.0
7 info lifecycle mylvue@0.0.0~preinstall: mylvue@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree

**Comment by anuxs** [comment]
I have resolved it , close this issue .
close #419
