### ISSUE TITLE
windows npm post install

### ISSUE THREAD

**Issue by miecio1212** [SimulatedGREG/electron-vue#46]
windows 8.1
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9

> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix app

Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at D:\tyrbambam\node_modules\eslint-friendly-formatter\index.js:181:73
    at Array.reduce (native)
    at module.exports (D:\tyrbambam\node_modules\eslint-friendly-formatter\index.js:157:17)
    at printResults (C:\Users\vanleif\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:84:14)
    at Object.execute (C:\Users\vanleif\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:192:17)
    at Object.<anonymous> (C:\Users\vanleif\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js:76:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by Luminess** [comment]
What's options have you selected in the vue-cli? I've left them all on default on Windows and it works perfectly.

**Comment by miecio1212** [comment]
default

**Comment by SimulatedGREG** [comment]
@miecio1212 Could you give this try on an earlier node version? There are some cases where some packages loose functionality if node releases some breaking changes.

**Comment by SimulatedGREG** [comment]
Closing for now. Feel free to comment back.
