### ISSUE TITLE
SyntaxError on clean install

### ISSUE THREAD

**Issue by AndreColli** [SimulatedGREG/electron-vue#460]
##### Console output

> SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at Object.module.exports.module.exports (D:\Documents\SlideTV\slidetv-app\dist\electron\main.js:4022:16)
      at __webpack_require__ (D:\Documents\SlideTV\slidetv-app\dist\electron\main.js:21:30)
      at App.<anonymous> (D:\Documents\SlideTV\slidetv-app\dist\electron\main.js:2600:26)
      at emitTwo (events.js:130:20)
      at App.emit (events.js:213:7)

##### Content of lines 4019 to 4023 in dist\main.js

> var IDMap = {};
var IDMapPath = _path2.default.resolve((0, _utils.getPath)(), 'IDMap.json');
if (_fs2.default.existsSync(IDMapPath)) {
  IDMap = JSON.parse(_fs2.default.readFileSync(IDMapPath, 'utf8'));
}

##### ENV
  * Node version: 8.9.1
  * NPM version: 5.5.1
  * vue-cli version: 2.9.1
  * Operating System: win10

**Comment by AndreColli** [comment]
[https://github.com/MarshallOfSound/electron-devtools-installer/issues/62](url)
