### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by sdyk-jym** [SimulatedGREG/electron-vue#464]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.

Hello everyone, I am in the construction of this error. I have not found a solution for a long time on the Internet. Can anyone tell me why this is? Thank you!
``` shell
 OKAY  take it away `electron-builder`

electron-builder 19.46.4
Error: Unresolved node modules: vue
    at /Users/qiqi/test/ev/node_modules/_electron-builder-lib@19.46.4@electron-builder-lib/src/util/packageDependencies.ts:112:19
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/async.js:17:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:400:19)
    at Promise._then (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:232:17)
    at Promise.then (/Users/qiqi/test/ev/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:125:17)
    at Object.args [as handler] (/Users/qiqi/test/ev/node_modules/_electron-builder@19.46.4@electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/qiqi/test/ev/node_modules/_yargs@10.0.3@yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/qiqi/test/ev/node_modules/_yargs@10.0.3@yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/qiqi/test/ev/node_modules/_yargs@10.0.3@yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/qiqi/test/ev/node_modules/_electron-builder@19.46.4@electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiqi/.npm/_logs/2017-11-23T11_05_03_791Z-debug.log
```

##### Tell me about your development environment.
  * Node version: v8.9.0
  * NPM version: v5.5.1
  * vue-cli version:  v2.9.1
  * Operating System: macOS 10.13.1 (17B48)

**Comment by kyjo2014** [comment]
i have met this problem too

**Comment by woo-long** [comment]
try to upgrade `electron-builder`

**Comment by Shing952** [comment]
```
OKAY  take it away `electron-builder`
electron-builder 19.48.2
Error: Unresolved node modules: webpack
    at E:\demo\my-project\node_modules\_electron-builder-lib@19.48.2@electron-builder-lib\src\util\packageDependencies.ts:112:19
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:689:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at Promise._then (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:232:17)
    at Promise.then (E:\demo\my-project\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:125:17)
    at Object.args [as handler] (E:\demo\my-project\node_modules\_electron-builder@19.48.2@electron-builder\out\cli\cli.js:127:117)
    at Object.runCommand (E:\demo\my-project\node_modules\_yargs@10.0.3@yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (E:\demo\my-project\node_modules\_yargs@10.0.3@yargs\yargs.js:1041:24)
    at Object.get [as argv] (E:\demo\my-project\node_modules\_yargs@10.0.3@yargs\yargs.js:957:21)
    at Object.<anonymous> (E:\demo\my-project\node_modules\_electron-builder@19.48.2@electron-builder\out\cli\cli.js:123:441)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

```
##### Tell me about your development environment.
Node version: v8.3.0
NPM version: v5.4.1
vue-cli version: v2.8.2
Operating System:  window 7

**Comment by Xiongzhenyu** [comment]
+1 
win10 is error, mac okay

**Comment by jamninetyfive** [comment]
upgrade  vue-template-compiler to slove it~。

**Comment by Sidfate** [comment]
win10 has the same question.

**Comment by mengdu** [comment]
我在公司电脑也遇到了同样的问题，后来在自己电脑打包既然没有问题，公司电脑采用 `cnpm install` 安装的依赖，我自己的电脑使用 `npm install`安装的依赖，现在已经打包成功了。
我觉得应该是阿里的源存在问题，或者说cnpm安装存在问题吧。

**Comment by zhuaofeide** [comment]
use yarn install all!!!!
