### ISSUE TITLE
serve with hot reload error 

### ISSUE THREAD

**Issue by lidashuang** [SimulatedGREG/electron-vue#51]
when run `npm run dev`

error msg： 
```
Starting electron...

electron  events.js:160
                throw er; // Unhandled 'error' event
                ^

          Error: spawn /Users/lidashuang/code/cc_activity/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ENOENT
              at exports._errnoException (util.js:1026:11)
              at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
              at onErrorNT (internal/child_process.js:359:16)
              at _combinedTickCallback (internal/process/next_tick.js:74:11)
              at process._tickCallback (internal/process/next_tick.js:98:9)
              at Module.runMain (module.js:609:11)
              at run (bootstrap_node.js:382:7)
              at startup (bootstrap_node.js:137:9)
              at bootstrap_node.js:497:3
```

#####  development environment.
  * Node version: v7.0.0
  * NPM version: 3.10.8
  * Operating System: macOS

**Comment by SimulatedGREG** [comment]
Could you give this try on an earlier node version? There are some cases where some packages loose functionality if node releases some breaking changes.

**Comment by SimulatedGREG** [comment]
Closing for now. Feel free to comment back.
