### ISSUE TITLE
[WINDOWS] Uncaught Error: A dynamic-link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by AlexVFornazieri** [SimulatedGREG/electron-vue#518]
* Electron version: 1.8.1
* Operating system: Windows 10 x64

Node is updated to last LTS version.

### Expected behavior
Application to run without errors, browser screen does not stand blank.
Like works in Ubuntu 16.04 LTS with any changes in code.

### Actual behavior
The error stack below is returned in the browser log, which is blank, processing is stopped.

ELECTRON_ASAR.js:173 Uncaught Error: A dynamic-link library (DLL) initialization routine failed. (Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.)
\\?\C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\bin\win32-x64-57\fibers.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\fibers.js:24:38)
    at Object.<anonymous> (C:\Users\alexv\Documents\maestroplayer\node_modules\fibers\fibers.js:27:3)

### How to reproduce
I don't have idea, i keep trying figure out, not is a Electron problem because electron-quick-start run normally in same PC. Thanks for any help.

**Comment by AlexVFornazieri** [comment]
Problem encountered, there was an import of a module called 'sync' (node-sync) that was not actually being used.

Import removed, with no more errors. Going to close.
