### ISSUE TITLE
Errors are nicely logged, but source map may be missing ?

### ISSUE THREAD

**Issue by marcelfalliere** [SimulatedGREG/electron-vue#579]
#### Found an issue or bug with electron-vue? Tell me all about it!
Running an electron app. 
Error gets thrown.
Console logs show stacktrace in `dist/` folder

##### Describe the issue / bug.
\#
The stacktrace logs should be mapped to `src/` folder and not `dist/`. Debugging is impossible with this. For example :

````
┏ Electron -------------------

  TypeError: Cannot read property 'simple' of undefined
      at new Logger (/Users/ba/Code/dice/electron-app/dist/electron/main.js:3993:64)
      at Object.<anonymous> (/Users/ba/Code/dice/electron-app/dist/electron/main.js:506:14)
      at Object.<anonymous> (/Users/ba/Code/dice/electron-app/dist/electron/main.js:549:30)
````

##### How can I reproduce this problem?
\#
thrown an error anywhere in your main or renderer process (I guess?) :
`throw new Error()`
Then look at the console running `npm run dev`

##### Tell me about your development environment.
  * Node version:v6.9.2
  * NPM version:5.7.1
  * vue-cli version: (if necessary)n/a
  * Operating System:Mac10.13.3

**Comment by Cdplourde** [comment]
I'm having this issue right now. Source maps for the main process seem to point to the dist folder, making debugging very difficult. Any solution for this?
