### ISSUE TITLE
Cannot read property 'on' of undefined (only in production)

### ISSUE THREAD

**Issue by Wuzi** [SimulatedGREG/electron-vue#598]
##### Describe the issue / bug.
I'm trying to load a model of sequelize, it works in `npm run dev`, but when building the application it is blank with the error: `Cannot read property 'on' of undefined`.

<details><summary>Full error</summary>
<p>

```js
Uncaught TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\Users\wuzi\Documents\Projects\electronvuetest\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:1008)
    at b (C:\Users\wuzi\Documents\Projects\electronvuetest\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:270)
    at module.exports.Object.defineProperty.value (C:\Users\wuzi\Documents\Projects\electronvuetest\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:630)
    at Object.<anonymous> (C:\Users\wuzi\Documents\Projects\electronvuetest\build\win-unpacked\resources\app.asar\dist\electron\main.js:1:639)
    at Object.<anonymous> (C:\Users\wuzi\Documents\Projects\electronvuetest\build\win-unpacked\resources\app.asar\dist\electron\main.js:2:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Sequelize.import
```

</p>
</details>

**Component.vue:**

```js
import Model from "../database/models"; // also tried with require

export default {
  name: "landing-page",
  components: { },
  data: function() {
    return {
      users: []
    };
  },
  created: function() {
    Model.User.findAll().then(users => {
      this.users = users;
    });
  }
};
```

##### How can I reproduce this problem?
I tried with a fresh application and the error persist.

- Create a fresh application
- Install sequelize and sqlite3
- Initialize sequelize project `sequelize init`
- Create a model and try to load it inside a vuejs component

I created a example project with this issue here: [repository](https://github.com/Wuzi/electronvuetest)
When using `npm run dev` it works fine, but the built app doesn't work.

##### If visual, provide a screenshot.
![image](https://image.ibb.co/ngO0W7/print.jpg)

##### Tell me about your development environment.
  * Node version: v8.11.1
  * NPM version: v5.6.0
  * vue-cli version: v2.9.3
  * Operating System: Windows

What can it be?
Thank you!

**Comment by Wuzi** [comment]
No luck so far, does anyone have any idea how to fix this?
Thanks.

**Comment by Wuzi** [comment]
Maybe the database files and .sequelizerc aren't being copied to the built app, should i add them somewhere?

**Comment by Wuzi** [comment]
Just to make it clearer:

It is having trouble trying to import this file (generated by sequelize init with slightly modifications) in the vuejs component:

```js
'use strict';

var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');
var basename = path.basename(__filename);
var env = process.env.NODE_ENV || 'development';
var config = require(__dirname + '/../config/config.json')[env];
var db = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.resolve(__dirname, file));
    db[model.name] = model;
  });

for (var modelName in db) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
}

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by Wuzi** [comment]
After debugging, I discovered that the problem is in this line:

```js
var model = sequelize['import'](path.resolve(__dirname, file));
db[model.name] = model;
```

So i commented it, and tried to import it direct from the component:

```html
<script>
var path = require('path');

import db from "../../database/models";
const User = db.sequelize['import'](path.resolve(__dirname, "../../database/models/user"));

export default {
  name: "landing-page",
  data: function() {
    return {
      users: []
    };
  },
  created: function() {
    User.findAll().then(users => {
      this.users = users;
    });
  },
  components: {},
  methods: {}
};
</script>
```

But now it says:

`Uncaught Error: Cannot find module '...\build\win-unpacked\resources\app.asar\database\models\user'`

**Comment by Wuzi** [comment]
So after some time reading the docs, i realized that it is a problem with path, since everything is packed together, i also changed the `import db from "../../database/models";` to `src/renderer/main.js`.

Is there a way for me to import the models correctly?

Since using __dirname here is not possible.
`var model = sequelize['import'](path.resolve(__dirname, file));`
