### ISSUE TITLE
Error when builiding for windows

### ISSUE THREAD

**Issue by pwnz22** [SimulatedGREG/electron-vue#628]
##### Describe the issue / bug.
Error when building for windows.
\#

##### How can I reproduce this problem?
Don't really know how to reproduce
\#

##### If visual, provide a screenshot.
`Error: Exit code: 1. Command failed: C:\Users\Erin\AppData\Local\electron-builder\cache\app-builder\app-builder-v0.6.1-x64\app-builder.exe icon --format ico --root C:\OpenServer\electron\first-app\build --root C:\OpenServer\electron\first-app --input build/icons/icon.ico
   ⨯ icon source "build/icons/icon.ico" not found
github.com/develar/app-builder/icons.resolveSourceFile
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:71
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:131
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:150
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
runtime.main
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:133
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:150
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
runtime.main
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/asm_amd64.s:2337

   ⨯ icon source "build/icons/icon.ico" not found
github.com/develar/app-builder/icons.resolveSourceFile
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:71
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:131
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:150
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
runtime.main
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/asm_amd64.s:2337
github.com/develar/app-builder/icons.ConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/icons/icon-converter.go:133
main.doConvertIcon
        /Users/develar/go/src/github.com/develar/app-builder/main.go:150
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:61
runtime.main
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.3/libexec/src/runtime/asm_amd64.s:2337

    at C:\OpenServer\electron\first-app\node_modules\builder-util\src\util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at exec (C:\OpenServer\electron\first-app\node_modules\builder-util\src\util.ts:85:3)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\platformPackager.ts:586:23
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1745:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at WinPackager.resolveIcon (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\platformPackager.js:623:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\platformPackager.ts:560:26
    at Generator.next (<anonymous>)
    at WinPackager.getOrConvertIcon (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\platformPackager.js:594:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:59:43)
    at Lazy.get value [as value] (C:\OpenServer\electron\first-app\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:195:27)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:292:33
    at Generator.next (<anonymous>)
    at WinPackager.signAndEditResources (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\winPackager.js:405:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:343:18
From previous event:
    at WinPackager.getOrConvertIcon (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\platformPackager.js:594:11)
    at Lazy.WinPackager._iconPath.Lazy (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:59:43)
    at Lazy.get value [as value] (C:\OpenServer\electron\first-app\node_modules\lazy-val\src\main.ts:18:23)
    at WinPackager.getIconPath (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:195:27)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:292:33
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signAndEditResources (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\winPackager.js:405:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\winPackager.ts:343:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\winPackager.js:423:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\platformPackager.ts:209:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\platformPackager.js:276:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\platformPackager.js:196:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\OpenServer\electron\first-app\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\OpenServer\electron\first-app\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\OpenServer\electron\first-app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\OpenServer\electron\first-app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (C:\OpenServer\electron\first-app\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\OpenServer\electron\first-app\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\OpenServer\electron\first-app\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\OpenServer\electron\first-app\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\OpenServer\electron\first-app\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\OpenServer\electron\first-app\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\OpenServer\electron\first-app\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\OpenServer\electron\first-app\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\OpenServer\electron\first-app\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\OpenServer\electron\first-app\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`
\#

##### Tell me about your development environment.
  * Node version: v8.9.4
  * NPM version: 6.1.0
  * vue-cli version: (if necessary)
  * Operating System: windows 10

**Comment by XanderLuciano** [comment]
>icon source "build/icons/icon.ico" not found

You're missing your `icon.ico` file. Either grab the .ico from the repo, or convert your existing icon to the .ico format with an online utility or remove the icon requirement from your build process (probably defined in your `package.json`).
