### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ducafecat** [SimulatedGREG/electron-vue#690]
```
# Install vue-cli and scaffold boilerplate
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project

# Install dependencies and run your app
cd my-project
yarn # or npm install
yarn run dev # or npm run dev
```

```
┏ Electron -------------------

  webpack:///./node_modules/electron-debug/index.js?:74
  	app.on('browser-window-created', (e, win) => {
  	    ^

  TypeError: Cannot read property 'on' of undefined
      at module.exports.opts (webpack:///./node_modules/electron-debug/index.js?:74:6)
      at eval (webpack:///./src/main/index.dev.js?:2:84)
      at Object../src/main/index.dev.js (/Users/hans/Documents/labs/my-project/dist/electron/main.js:494:1)
      at __webpack_require__ (/Users/hans/Documents/labs/my-project/dist/electron/main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)
      at Object.0 (/Users/hans/Documents/labs/my-project/dist/electron/main.js:517:1)
      at __webpack_require__ (/Users/hans/Documents/labs/my-project/dist/electron/main.js:21:30)
      at /Users/hans/Documents/labs/my-project/dist/electron/main.js:85:18
      at Object.<anonymous> (/Users/hans/Documents/labs/my-project/dist/electron/main.js:88:10)
      at Object.<anonymous> (/Users/hans/Documents/labs/my-project/dist/electron/main.js:632:3)

┗ ----------------------------
```

**Comment by Akumzy** [comment]
Full code will help
