### ISSUE TITLE
npm run build on ubuntu 16.04 and ubuntu 18.04

### ISSUE THREAD

**Issue by yankunsam** [SimulatedGREG/electron-vue#760]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
 OKAY  take it away `electron-builder`

  • electron-builder version=20.36.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build/builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=1.8.8 appOutDir=build/linux-unpacked
  • building        target=snap arch=x64 file=build/saas_0.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=build/saas-0.0.0-x86_64.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • default Electron icon is used reason=application icon is not set
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  ⨯ at least snapcraft 2.40.0 is required, please: sudo snap install snapcraft --classic
Error: /home/sam/Public/saas/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/sam/Public/saas/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
From previous event:
    at SnapTarget.build (/home/sam/Public/saas/node_modules/app-builder-lib/src/targets/snap.ts:146:44)
    at Function.buildAsyncTargets (/home/sam/Public/saas/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/sam/Public/saas/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/sam/Public/saas/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.pack (/home/sam/Public/saas/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:406:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/sam/Public/saas/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/sam/Public/saas/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at Packager.doBuild (/home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:372:24)
    at /home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:342:57
    at Generator.next (<anonymous>)
    at /home/sam/Public/saas/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/sam/Public/saas/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:311:133)
    at /home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:307:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/sam/Public/saas/node_modules/app-builder-lib/src/packager.ts:264:14)
    at build (/home/sam/Public/saas/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/sam/Public/saas/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/sam/Public/saas/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saas@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by kevinma0819** [comment]
Have the exactly same issue for release on Ubuntu 18.04, even though I did "sudo snap install snapcraft --classic" and the current version of snapcraft is 2.43.1. Looking for a solution.

**Comment by zmj97** [comment]
+1
