### ISSUE TITLE
try to use a native addon，but can't run

### ISSUE THREAD

**Issue by cfy2015** [SimulatedGREG/electron-vue#786]
App threw an error during load
  Error: Cannot find module '../lib/node_modules/zoomsdk/build/Release/zoomsdk'
      at webpackEmptyContext (webpack:///./src/lib_sync?:2:10)
      at init (webpack:///./src/lib/zoom_sdk.js?:66:68)
      at Object.getInstance (webpack:///./src/lib/zoom_sdk.js?:155:28)
      at eval (webpack:///./src/main/index.js?:12:34)
      at Object../src/main/index.js (C:\Users\Administrator\Desktop\my-project\dist\electron\main.js:1533:1)
      at __webpack_require__ (C:\Users\Administrator\Desktop\my-project\dist\electron\main.js:21:30)
      at eval (webpack:///./src/main/index.dev.js?:12:1)
      at Object../src/main/index.dev.js (C:\Users\Administrator\Desktop\my-project\dist\electron\main.js:1521:1)
      at __webpack_require__ (C:\Users\Administrator\Desktop\my-project\dist\electron\main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)

  * Node version:v8.12.0
  * NPM version:6.4.1
  * vue-cli version: (if necessary)
  * Operating System:win10 1703

**Comment by xinyang3** [comment]
in the render process, require a native module, i catch an error

|-- src
|-- main
   |-- a.js
   |-- index.js
|-- render 
   |-- section/talk
      |-- index.js
in sections/talk/index.js
`const remote = require('electron').remote
const engine = remote.require('./a')
console.log(a)`

Uncaught Error: Cannot find module './a'
Require stack:
- D:\zxy\electron-action\chat\dist\electron\main.js
- D:\zxy\electron-action\chat\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7736)
    at Module._load (internal/modules/cjs/loader.js:690)
    at Module._load (electron/js2c/asar.js:738)
    at Function.Module._load (electron/js2c/asar.js:738)
    at Module.require (internal/modules/cjs/loader.js:852)
    at electron/js2c/browser_init.js:6936
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6896)
    at IpcMainImpl.emit (events.js:223)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:4115)

**Comment by joshuafc** [comment]
do you guys solved the problem?
