### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by cmzz** [SimulatedGREG/electron-vue#80]
```
➜  my-project npm run dev

> my-project@0.0.0 dev /Users/zyxcba/my-project
> node tasks/runner.js

Starting webpack-dev-server...

webpack  events.js:160
               throw er; // Unhandled 'error' event
               ^

         Error: listen EADDRNOTAVAIL 192.168.33.10:19081
             at Object.exports._errnoException (util.js:1022:11)
             at exports._exceptionWithHostPort (util.js:1045:20)
             at Server._listen2 (net.js:1249:19)
             at listen (net.js:1298:10)
             at doListening (net.js:1397:7)
             at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
             at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

What's wrong.  Thank you!

**Comment by cmzz** [comment]
And why thd ip is 192.168.33.10?  That's my virtual machine's ip, but it's closed.

**Comment by cmzz** [comment]
Now I'm waiting online ......

**Comment by SimulatedGREG** [comment]
@cmzz 

I understand you are using a virtual machine, but I'm not entirely sure why the IP changed instead of using the default `localhost`. I'm assuming you changed some configuration considering the port number is also different.

```
Error: listen EADDRNOTAVAIL 192.168.33.10:19081
```
It would seem maybe you have another running instance, or a previous instance wasn't properly closed.

**Comment by cmzz** [comment]
@SimulatedGREG  Thank you.  

I delete this config in my hosts, the its work: 
`192.168.33.10 localhost`
