### ISSUE TITLE
Build failed with error code: 1

### ISSUE THREAD

**Issue by iamzaizai** [SimulatedGREG/electron-vue#806]
`yarn install v1.13.0
warning package.json: No license field
info No lockfile found.
warning cuni@0.0.1: No license field
[1/4] Resolving packages...
warning babili-webpack-plugin > babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⡀ electron
**error E:\project\cuni\node_modules\node-sass: Command failed.**
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\project\cuni\node_modules\node-sass
Output:
Building: E:\Program Files\nodejs\node.exe E:\project\cuni\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'E:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\project\\cuni\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\project\cuni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\project\cuni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\project\cuni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\project\cuni\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\project\cuni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\project\cuni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\project\cuni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\project\cuni\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\project\\cuni\\node_modules\\which\\which.js:13:12)\n    at F (E:\\project\\cuni\\node_modules\\which\\which.js:68:19)\n    at E (E:\\project\\cuni\\node_modules\\which\\which.js:80:29)\n    at E:\\project\\cuni\\node_modules\\which\\which.js:89:16\n    at E:\\project\\cuni\\node_modules\\isexe\\index.js:42:5\n    at E:\\project\\cuni\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\project\cuni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\project\cuni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\project\cuni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\project\cuni\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\project\cuni\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\project\cuni\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\project\cuni\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\project\cuni\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\project\cuni\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (E:\\project\\cuni\\node_modules\\which\\which.js:13:12)\n    at F (E:\\project\\cuni\\node_modules\\which\\which.js:68:19)\n    at E (E:\\project\\cuni\\node_modules\\which\\which.js:80:29)\n    at E:\\project\\cuni\\node_modules\\which\\which.js:89:16\n    at E:\\project\\cuni\\node_modules\\isexe\\index.js:42:5\n    at E:\\project\\cuni\\node_modules\\isexe\\windows.js:36:5\n    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\project\cuni\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\project\cuni\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\project\cuni\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\project\\cuni\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\project\cuni\node_modules\node-sass
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
`

**Comment by iamzaizai** [comment]
yarn install v1.13.0
warning package.json: No license field
info No lockfile found.
warning cuni@0.0.1: No license field
[1/4] Resolving packages...
warning babili-webpack-plugin > babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile 'C:\\Users\\仔仔\\AppData\\Local\\Yarn\\Cache\\v4\\npm-ansi-styles-2.2.1-b432dd3358b634cf75e1e4664368240533c1ddbe\\node_modules\\ansi-styles\\package.json' -> 'E:\\project\\cuni\\node_modules\\node-sass\\node_modules\\ansi-styles\\package.json'".
info If you think this is a bug, please open a bug report with the information provided in "E:\\project\\cuni\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
