### ISSUE TITLE
urgent--npm run build error

### ISSUE THREAD

**Issue by DamnTime** [SimulatedGREG/electron-vue#853]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=build\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=2.0.18 appOutDir=build\win-unpacked
  ⨯ remove D:\ync-merchant\build\win-unpacked\resources\app.asar: The process cannot access the file because it is being used by another process.
github.com/develar/go-fs-util.EnsureEmptyDir
        /Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:101
github.com/develar/app-builder/pkg/electron.unpackElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:39
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

Error: D:\ync-merchant\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\ync-merchant\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

##### How can I reproduce this problem?
\#When I run NPM run build, but, When I restart the computer, NPM run build again and succeeded. 

##### Tell me about your development environment.
  * Node version: 10.15.3
  * NPM version: 6.9.0
  * vue-cli version: (if necessary)
  * Operating System:win32

**Comment by SheenOh** [comment]
@DamnTime 
i got the same problem.  did you solved it?

**Comment by JennisX** [comment]
主要是因为打包需要的依赖包没有下载下来导致打包失败，可以参考下面网友的踩坑教程：
https://segmentfault.com/a/1190000018533945?utm_source=tag-newest
