### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by xiaomizhou66** [SimulatedGREG/electron-vue#860]
```BASH
Error: C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at _unpack (C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\app-builder-lib\out\electron\ElectronFramework.js:298:18)
    at unpack (C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\app-builder-lib\out\electron\ElectronFramework.js:257:18)
    at ElectronFramework.prepareApplicationStageDirectory (C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\app-builder-lib\src\electron\ElectronFramework.ts:125:12)
    at C:\Users\liuxm\work\electron\electron-vue-demo-WeChat\node_modules\app-builder-lib\src\platformPackager.ts:180:21
    at Generator.next (<anonymous>)
```

**Comment by linuxjuggler** [comment]
Can you provide more information about your build environment? also showing your `package.json` file would help too.
