### ISSUE TITLE
electron-vue and serialport.js. import problem.

### ISSUE THREAD

**Issue by basitiyidir** [SimulatedGREG/electron-vue#872]
I want to communicate with com port using the electron-vue and serialport.js.

I can't import.

yarn add serialport

```
<template>
    <div>
        
    </div>
</template>


<script>

import SerialPort from 'serialport'


export default {
    data () {
        return {

        }
    },

}
}
</script>
```

I'm getting an error.

`Uncaught TypeError: Cannot read property 'indexOf' of undefined`

Can you help me.

**Comment by basitiyidir** [comment]
Solution
http://meow.noopkat.com/using-node-serialport-in-an-electron-app/
https://github.com/rwaldron/johnny-five/issues/1379

**Comment by thrazu** [comment]
My enviroment:
```
Vue.js: 2.6.10
Electron: 2.0.18
Node: 8.9.3
Platform: linux
```
If you are using Eletron with Vue.js you need to rebuild the serialport module doing something like this:
```
npm install electron-rebuild
```
after this, you can add in your package.json > section "scripts", another line saying:
```
"rebuild": "electron-rebuild -f -w serialport"
```
You can rebuild the module with terminal command
```
npm run rebuild
```
Now the serialport module should be imported and will work as expected. Goog luck!

**Comment by katletkis** [comment]
I still have this issue in my electron-vue app:
``` 
let SerialPort = require("serialport");
SerialPort.list();
```
throws the following error:
```
(node:50986) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/@serialport/bindings/lib/linux.js?:2:91)
    at Object../node_modules/@serialport/bindings/lib/linux.js (/home/triton/js/electron-vue-serialport-rebuild/dist_electron/index.js:151:1)
    at __webpack_require__ (/home/triton/js/electron-vue-serialport-rebuild/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/@serialport/bindings/lib/index.js?:14:22)
    at Object../node_modules/@serialport/bindings/lib/index.js (/home/triton/js/electron-vue-serialport-rebuild/dist_electron/index.js:118:1)
    at __webpack_require__ (/home/triton/js/electron-vue-serialport-rebuild/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/serialport/lib/index.js?:2:17)
    at Object../node_modules/serialport/lib/index.js (/home/triton/js/electron-vue-serialport-rebuild/dist_electron/index.js:1891:1)
(node:50986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

package.json file:
```
{
  "name": "electron-vue-serialport-rebuild",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "buildDependenciesFromSource": "true",
    "rebuild": "$(npm bin)/electron-rebuild",
    "rebuild-serialport": "electron-rebuild -f -w serialport"
  },
  "electron:build": {
    "buildDependenciesFromSource": true,
    "npmRebuild": false
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "serialport": "^9.2.1",
    "usb": "^1.7.2",
    "usb-cdc-acm": "^0.1.1",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^3.2.0"
  }
  "devDependencies": {
    "@types/electron-devtools-installer": "^2.2.0",
    "@types/serialport": "^8.0.2",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "electron": "^14.0.1",
    "electron-devtools-installer": "^3.1.0",
    "electron-rebuild": "^3.2.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "typescript": "~4.1.5",
    "vue-cli-plugin-electron-builder": "~2.1.1",
    "vue-template-compiler": "^2.6.11"
  }
}
```


my platform:
Vue: 2.6.14
Electron: 14.0.1
Node: 14.17.0
Platform: linux

please help

**Comment by katletkis** [comment]
Nevermind I forgot to add 'serialport' as an external in my 'vue.config.js' file. Thanks [feeh27](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/427#issue-484189652).

```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['serialport']
        }
    }
};
```
