### ISSUE TITLE
Application entry file "background.js" does not exist

### ISSUE THREAD

**Issue by DatMoser** [SimulatedGREG/electron-vue#875]
When I try to to build my app with "yarn build" it starts, but then fails with " Error: Application entry file "background.js" in the "/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/build/mac/boxorganiser.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration."

I can even see how the build directory is created and a main.js file placed inside it, instead of a background.js. But I have no idea how I should react to this.

Error-message:
````
Error: Application entry file "background.js" in the "/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/build/mac/boxorganiser.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/out/asar/asarFileChecker.js:44:14)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at _checkFileInArchive (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:36:17)
    at checkFileInArchive (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/out/asar/asarFileChecker.js:40:30)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:406:110)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:446:92)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at MacPackager.doPack (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/macPackager.ts:88:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at Packager.doBuild (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at Packager._build (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/<name>/Documents/<name>/Programmierungen/boxorganiser/node_modules/electron-builder/src/cli/cli.ts:46:19)

````

My package.json:
`````
{
  "name": "boxorganiser",
  "version": "0.0.1",
  "description": "Simple box-organiser",
  "author": "<name>",
  "scripts": {
    "build": "node .electron-vue/build.js && electron-builder",
    "test": "npm run unit && npm run e2e",
    "e2e": "npm run pack && mocha test/e2e",
    "lint": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src test",
    "build:clean": "cross-env BUILD_TARGET=clean node .electron-vue/build.js",
    "build:dir": "node .electron-vue/build.js && electron-builder --dir",
    "build:web": "cross-env BUILD_TARGET=web node .electron-vue/build.js",
    "dev": "node .electron-vue/dev-runner.js",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "lint:fix": "eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src test",
    "pack": "npm run pack:main && npm run pack:renderer",
    "pack:main": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.main.config.js",
    "pack:renderer": "cross-env NODE_ENV=production webpack --progress --colors --config .electron-vue/webpack.renderer.config.js",
    "postinstall": "npm run lint:fix && electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "unit": "karma start test/unit/karma.conf.js"
  },
  "main": "background.js",
  "dependencies": {
    "axios": "^0.18.0",
    "firebase": "^5.11.0",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-istanbul": "^4.1.6",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^2.1.2",
    "chai": "^4.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.4",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "inject-loader": "^4.0.1",
    "karma": "^2.0.2",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.2",
    "karma-electron": "^6.0.0",
    "karma-mocha": "^1.3.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "^0.0.32",
    "karma-webpack": "^3.0.0",
    "mini-css-extract-plugin": "0.4.0",
    "mocha": "^5.2.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "node-sass": "^4.9.2",
    "require-dir": "^1.0.0",
    "sass-loader": "^7.0.3",
    "spectron": "^3.8.0",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-cli-plugin-electron-builder": "^1.3.2",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  },
  "build": {
    "productName": "boxorganiser",
    "appId": "de.boxorganiser.app",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
  "license": "MIT"
}
`````

and my main.js:
````
import Vue from 'vue'
import axios from 'axios'
import firebase from 'firebase'

import App from './App'
import router from './router'
import store from './store'

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))
Vue.http = Vue.prototype.$http = axios
Vue.config.productionTip = false

var firebaseConfig = {
  // just firebase stuff
}
// Initialize Firebase
firebase.initializeApp(firebaseConfig)

/* eslint-disable no-new */
new Vue({
  components: { App },
  router,
  store,
  template: '<App/>'
}).$mount('#app')
````
Everything works perfectly when I run it in dev mode, but as soon as I switch to build it fails.

  * Node version: 10.15.3
  * NPM version: 6.4.1
  * vue-cli version: 3.7.0
  * Operating System: Mac os 10.14.4 (18E226)

I really hope, that somebody can help me with that, because I've already put too much work into this project to start all over again. :`(

**Comment by linuxjuggler** [comment]
The `main` option should have the full path to your file for example `./dist/electron/background.js`.

also, make sure to edit the webpack configuration to use `background.js` too.

**Comment by DatMoser** [comment]
Thanks for the quick response, but I'm quite new to electron-vue / webpack, so could you please specify, where and how I can change the configuration to support the background.js. Google couldn't help me with that and in my .electron-vue folder I have following files:

- build.js
- dev-client
- dev-runner
- webpack.main.config.js
- webpack.renderer.config.js
- webpack.web.config.js

or do I somehow specify webpack options in my package.json?

Thanks in advance! :)

**Comment by linuxjuggler** [comment]
If you are new, I advise you not to change any of the default values of the projects.
you need to change the corresponded webpack file depends on what `background.js` is responsible to do.

if it is a replacement of `/src/main/index.js` then you should edit `webpack.main.config.js` and replace every place where `index.js` is mentioned.

but again, since you are new to electron-vue / webpack, it is much better to keep the default values as is, till you get more information about how electron-vue is using webpack, then you can change anything based on your own preferences.
