### ISSUE TITLE
electron packager cannot build for windows anymore since upgrading to OSX 10.15

### ISSUE THREAD

**Issue by neuronflow** [SimulatedGREG/electron-vue#937]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#

When trying to package on OSX:

Packaging app for platform mas x64 using electron v4.1.4
Packaging app for platform darwin x64 using electron v4.1.4
Packaging app for platform win32 x64 using electron v4.1.4
Packaging app for platform linux x64 using electron v4.1.4
        WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.
Unhandled rejection Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at module.exports (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/rcedit/lib/rcedit.js:47:15)
    at P (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:32:6)
    at new Promise (<anonymous>)
    at /Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:6:9
    at ret (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:56:76)
    at getIconPath.then.icon (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/win32.js:95:39)

##### How can I reproduce this problem?
\#
upgrade to OSX 10.15 type `yarn run build`

##### Tell me about your development environment.
  * Node version: 10.16.3
  * NPM version: 6.9.0
  * vue-cli version: (if necessary)
  * Operating System: OSX 10.15

**Comment by thaddeusm** [comment]
As of OSX 10.15, Apple no longer supports 32-bit applications such as Wine, which is used to package apps for Windows.

There is [an open issue related to this on the Electron-Builder repo](https://github.com/electron-userland/electron-builder/issues/4305).

After looking for a solution for several days, I tried building it from a Docker image instead on my local machine.  It was my first time to ever use Docker but it was simple to accomplish just by following [this documentation from Electron-Builder](https://www.electron.build/multi-platform-build#build-electron-app-using-docker-on-a-local-machine).
