### ISSUE TITLE
npm run dev  SyntaxError

### ISSUE THREAD

**Issue by yangjiakun326** [SimulatedGREG/electron-vue#950]
##### Describe the issue / bug.
\# I do npm run  dev without any modify,but tell me about:
  SyntaxError: Unexpected token {
      at Object../node_modules/electron-localshortcut/index.js (D:\my-project\dist\electron\main.js:249:1)
      at __webpack_require__ (D:\my-project\dist\electron\main.js:21:30)

##### How can I reproduce this problem?
\#
under windows system (Node version: 10.16.0), init project, npm/yarn install, npm run dev

##### If visual, provide a screenshot.
\#

┏ Electron -------------------

  App threw an error during load

┗ ----------------------------

┏ Electron -------------------

  SyntaxError: Unexpected token {
      at Object../node_modules/electron-localshortcut/index.js (D:\my-project\dist\electron\main.js:249:1)
      at __webpack_require__ (D:\my-project\dist\electron\main.js:21:30)
      at eval (webpack:///./node_modules/electron-debug/index.js?:3:23)
      at Object../node_modules/electron-debug/index.js (D:\my-project\dist\electron\main.js:177:1)
      at __webpack_require__ (D:\my-project\dist\electron\main.js:21:30)
      at eval (webpack:///./src/main/index.dev.js?:2:1)
      at Object../src/main/index.dev.js (D:\my-project\dist\electron\main.js:517:1)
      at __webpack_require__ (D:\my-project\dist\electron\main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)
      at Object.0 (D:\my-project\dist\electron\main.js:540:1)

┗ ----------------------------

##### Tell me about your development environment.
  * Node version: v10.16.0
  * NPM version: 6.9.0
  * vue-cli version: (if necessary) 2.9.6
  * Operating System: win10 X64

**Comment by ROTGP** [comment]
Me too

**Comment by yangjiakun326** [comment]
> Me too

I solve this problem. yarn add electron-localshortcut@3.1.0
