### ISSUE TITLE
Not working on Windows.

### ISSUE THREAD

**Issue by sgehrman** [SimulatedGREG/electron-vue#99]
$ vue init simulatedgreg/electron-vue my-project

c:\Users\Steve\AppData\Roaming\npm\node_modules\vue-cli\node_modules\metalsmith\lib\index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Steve\AppData\Roaming\npm\node_modules\vue-cli\node_modules\metalsmith\index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by citycide** [comment]
Are you using a Node version < v4, like 0.12 or 0.10? You can check by running `node -v` and this type of thing is always helpful when reporting issues.

The error is over the `*` which signifies a [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*). These aren't supported in 0.x versions of Node, support for all of which has been dropped by Node.

If you _are_ on one of those super old versions, you should definitely upgrade to at least the latest 6.x which is stable, or 7.x if you want stable + some new hotness.

**Comment by SimulatedGREG** [comment]
@sgehrman 

Please respond if @citycide's advice helps. Thanks.

**Comment by sgehrman** [comment]
Sorry, i thought I had the latest node, but i guess not. I'm on Windows and installed it and have this.

$ node -v
v0.10.17

 $ npm -v
3.10.10

I'll update, thanks.

**Comment by SimulatedGREG** [comment]
@sgehrman 

No problem. I would definitely recommend upgrading to the latest LTS or higher. `v0.12.7` and below are now officially deprecated.
